---
- name: Install and configure MongoDB on RHEL 9
  hosts: all
  become: yes  # Run tasks with root privileges

  tasks:
    - name: Install required packages for MongoDB repository
      ansible.builtin.dnf:
        name:
          - curl
          - gnupg
        state: present

    - name: Import MongoDB GPG key
      ansible.builtin.get_url:
        url: https://pgp.mongodb.com/server-7.0.asc
        dest: /tmp/mongodb-server-7.0.asc
        mode: '0644'

    - name: Import GPG key into RPM
      ansible.builtin.command:
        cmd: rpm --import /tmp/mongodb-server-7.0.asc
      changed_when: false

    - name: Create MongoDB repository file
      ansible.builtin.copy:
        content: |
          [mongodb-org-7.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://pgp.mongodb.com/server-7.0.asc
        dest: /etc/yum.repos.d/mongodb-org-7.0.repo
        mode: '0644'

    - name: Install MongoDB packages
      ansible.builtin.dnf:
        name:
          - mongodb-org
        state: present
        update_cache: yes

    - name: Create MongoDB data directory
      ansible.builtin.file:
        path: /var/lib/mongo
        state: directory
        owner: mongod
        group: mongod
        mode: '0755'

    - name: Create MongoDB log directory
      ansible.builtin.file:
        path: /var/log/mongodb
        state: directory
        owner: mongod
        group: mongod
        mode: '0755'

    - name: Create MongoDB PID file directory
      ansible.builtin.file:
        path: /var/run/mongodb
        state: directory
        owner: mongod
        group: mongod
        mode: '0755'

    - name: Configure MongoDB (mongod.conf)
      ansible.builtin.copy:
        content: |
          # mongod.conf
          
          # for documentation of all options, see:
          #   http://docs.mongodb.org/manual/reference/configuration-options/
          
          # Where to write logging data.
          systemLog:
            destination: file
            logAppend: true
            path: /var/log/mongodb/mongod.log
          
          # Where and how to store data.
          storage:
            dbPath: /var/lib/mongo
            journal:
              enabled: true
          
          # how the process runs
          processManagement:
            fork: true
            pidFilePath: /var/run/mongodb/mongod.pid
            timeZoneInfo: /usr/share/zoneinfo
          
          # network interfaces
          net:
            port: 27017
            bindIp: 127.0.0.1
          
          #security:
          #  authorization: enabled
        dest: /etc/mongod.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes
      notify: Restart MongoDB

    - name: Ensure MongoDB service is running and enabled
      ansible.builtin.systemd:
        name: mongod
        state: started
        enabled: yes

    - name: Open MongoDB port (27017) in firewalld
      ansible.posix.firewalld:
        port: 27017/tcp
        permanent: yes
        state: enabled
      notify: Reload firewalld

  handlers:
    - name: Restart MongoDB
      ansible.builtin.service:
        name: mongod
        state: restarted

    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded

