---
- name: Uninstall and remove MongoDB from RHEL 9
  hosts: all
  become: yes  # Run tasks with root privileges

  tasks:
    - name: Stop MongoDB service
      ansible.builtin.systemd:
        name: mongod
        state: stopped
      ignore_errors: yes

    - name: Disable MongoDB service
      ansible.builtin.systemd:
        name: mongod
        enabled: no
      ignore_errors: yes

    - name: Remove MongoDB port (27017) from firewalld
      ansible.posix.firewalld:
        port: 27017/tcp
        permanent: yes
        state: disabled
      notify: Reload firewalld
      ignore_errors: yes

    - name: Remove MongoDB configuration file
      ansible.builtin.file:
        path: /etc/mongod.conf
        state: absent

    - name: Remove MongoDB packages
      ansible.builtin.dnf:
        name:
          - mongodb-org
          - mongodb-org-server
          - mongodb-org-mongos
          - mongodb-org-shell
          - mongodb-org-tools
        state: absent
      ignore_errors: yes

    - name: Remove MongoDB repository file
      ansible.builtin.file:
        path: /etc/yum.repos.d/mongodb-org-7.0.repo
        state: absent

    - name: Get MongoDB GPG key ID
      ansible.builtin.shell:
        cmd: rpm -qa gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\n' | grep -i mongodb || true
      register: mongodb_gpg_keys
      changed_when: false
      failed_when: false

    - name: Remove MongoDB GPG key from RPM
      ansible.builtin.command:
        cmd: rpm -e {{ item }}
      loop: "{{ mongodb_gpg_keys.stdout_lines }}"
      when: mongodb_gpg_keys.stdout_lines | length > 0
      ignore_errors: yes

    - name: Remove temporary GPG key file
      ansible.builtin.file:
        path: /tmp/mongodb-server-7.0.asc
        state: absent

    - name: Remove MongoDB PID file directory
      ansible.builtin.file:
        path: /var/run/mongodb
        state: absent

    - name: Remove MongoDB log directory
      ansible.builtin.file:
        path: /var/log/mongodb
        state: absent

    - name: Remove MongoDB data directory
      ansible.builtin.file:
        path: /var/lib/mongo
        state: absent
      # WARNING: This will delete all MongoDB data!
      # Comment out or remove this task if you want to preserve data

  handlers:
    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded

