---
# Ansible Galaxy requirements file
# Install collections with: ansible-galaxy collection install -r requirements.yml

collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.mongodb
    version: ">=1.6.0"

